# Change these first
owner: muyan556   
repo: upptime   

sites:
  - name: Server  
    url: https://muyan556.serv00.net
  - name: Blog
    url: https://muyan.us.kg  

status-website:  
  baseUrl: /upptime
  name: Website    

# Upptime also supports notifications, assigning issues, and more    
# See https://upptime.js.org/docs/configuration  
